
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Brain, CheckCircle, XCircle, Trophy, Play, Loader2, Sparkles, RefreshCw } from 'lucide-react';
import { generateTriviaQuestion } from '../services/geminiService';

interface TriviaQuestion {
  question: string;
  options: string[];
  correctAnswer: string;
  reference: string;
}

const BibleTrivia: React.FC = () => {
  const [gameState, setGameState] = useState<'start' | 'loading' | 'playing' | 'result'>('start');
  const [currentQuestion, setCurrentQuestion] = useState<TriviaQuestion | null>(null);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [isCorrect, setIsCorrect] = useState<boolean | null>(null);
  const [score, setScore] = useState(0);
  const [streak, setStreak] = useState(0);

  const fetchQuestion = async () => {
    setGameState('loading');
    setSelectedOption(null);
    setIsCorrect(null);
    try {
      const q = await generateTriviaQuestion();
      setCurrentQuestion(q);
      setGameState('playing');
    } catch (e) {
      console.error(e);
      // If error, maybe go back to start or show error state
      setGameState('start');
    }
  };

  const handleStart = () => {
    setScore(0);
    setStreak(0);
    fetchQuestion();
  };

  const handleAnswer = (option: string) => {
    if (selectedOption || !currentQuestion) return;
    
    setSelectedOption(option);
    const correct = option === currentQuestion.correctAnswer;
    setIsCorrect(correct);
    
    if (correct) {
      setScore(s => s + 10 + (streak * 2));
      setStreak(s => s + 1);
    } else {
      setStreak(0);
    }
  };

  const handleNext = () => {
    fetchQuestion();
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-12">
       {/* Header */}
       <div className="bg-church-900 text-white pt-20 pb-24 px-4 relative overflow-hidden">
         <div className="absolute top-0 right-0 w-96 h-96 bg-purple-600 rounded-full blur-[100px] opacity-20"></div>
         <div className="absolute bottom-0 left-0 w-80 h-80 bg-gold-600 rounded-full blur-[100px] opacity-10"></div>
         
         <div className="max-w-3xl mx-auto relative z-10 text-center">
            <Link to="/portal" className="absolute left-0 top-0 inline-flex items-center text-church-300 hover:text-white transition">
                <ArrowLeft size={16} className="mr-2" /> Exit
            </Link>
            <div className="inline-flex items-center justify-center p-3 bg-white/10 rounded-full mb-6 backdrop-blur-sm border border-white/10 shadow-lg">
                <Brain size={32} className="text-gold-400" />
            </div>
            <h1 className="text-4xl md:text-5xl font-serif font-bold mb-4">Bible Trivia</h1>
            <p className="text-church-200 text-lg">Test your knowledge and sharpen your spirit.</p>
         </div>
      </div>

      <div className="max-w-2xl mx-auto px-4 -mt-16 relative z-20">
        
        {/* Game Container */}
        <div className="bg-white rounded-3xl shadow-2xl overflow-hidden border border-gray-100 min-h-[400px] flex flex-col">
            
            {/* Top Bar (Score) */}
            {(gameState === 'playing' || gameState === 'loading') && (
                <div className="px-6 py-4 bg-gray-50 border-b border-gray-100 flex justify-between items-center">
                    <div className="flex items-center gap-2">
                        <Trophy size={18} className="text-gold-500" />
                        <span className="font-bold text-gray-900">{score} pts</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <span className="text-xs font-bold text-church-500 uppercase tracking-widest">Streak</span>
                        <div className="flex">
                            {[...Array(3)].map((_, i) => (
                                <div key={i} className={`w-2 h-2 rounded-full mx-0.5 ${i < streak ? 'bg-green-500' : 'bg-gray-200'}`}></div>
                            ))}
                        </div>
                    </div>
                </div>
            )}

            {/* Content Area */}
            <div className="flex-1 p-8 flex flex-col items-center justify-center text-center">
                
                {gameState === 'start' && (
                    <div className="animate-fade-in-up">
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">Ready to play?</h2>
                        <p className="text-gray-600 mb-8">Questions are generated by AI from across the Scriptures. Challenge yourself!</p>
                        <button 
                            onClick={handleStart}
                            className="bg-church-600 text-white px-10 py-4 rounded-full font-bold text-lg hover:bg-church-700 transition shadow-lg hover:scale-105 flex items-center gap-2 mx-auto"
                        >
                            <Play size={20} /> Start Game
                        </button>
                    </div>
                )}

                {gameState === 'loading' && (
                    <div className="flex flex-col items-center gap-4 animate-pulse">
                        <Loader2 size={48} className="animate-spin text-church-600" />
                        <p className="font-bold text-church-500">Preparing question...</p>
                    </div>
                )}

                {gameState === 'playing' && currentQuestion && (
                    <div className="w-full max-w-lg animate-scale-in">
                        <h2 className="text-xl md:text-2xl font-bold text-gray-900 mb-8 leading-relaxed">
                            {currentQuestion.question}
                        </h2>
                        
                        <div className="space-y-3 mb-8">
                            {currentQuestion.options.map((option, idx) => {
                                let btnClass = "w-full p-4 rounded-xl border-2 text-left font-medium transition-all duration-200 flex justify-between items-center group ";
                                if (selectedOption === null) {
                                    btnClass += "border-gray-100 hover:border-church-400 hover:bg-church-50 text-gray-700";
                                } else if (option === currentQuestion.correctAnswer) {
                                    btnClass += "border-green-500 bg-green-50 text-green-700";
                                } else if (option === selectedOption && option !== currentQuestion.correctAnswer) {
                                    btnClass += "border-red-500 bg-red-50 text-red-700";
                                } else {
                                    btnClass += "border-gray-100 opacity-50";
                                }

                                return (
                                    <button 
                                        key={idx}
                                        onClick={() => handleAnswer(option)}
                                        disabled={selectedOption !== null}
                                        className={btnClass}
                                    >
                                        <span className="flex items-center gap-3">
                                            <span className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${selectedOption === null ? 'bg-gray-100 text-gray-500 group-hover:bg-white' : ''}`}>
                                                {String.fromCharCode(65 + idx)}
                                            </span>
                                            {option}
                                        </span>
                                        {selectedOption !== null && option === currentQuestion.correctAnswer && <CheckCircle size={20} className="text-green-600" />}
                                        {selectedOption === option && option !== currentQuestion.correctAnswer && <XCircle size={20} className="text-red-600" />}
                                    </button>
                                );
                            })}
                        </div>

                        {selectedOption && (
                            <div className="animate-fade-in">
                                <div className={`p-4 rounded-xl mb-6 flex items-start gap-3 text-left ${isCorrect ? 'bg-green-100 text-green-800' : 'bg-orange-100 text-orange-800'}`}>
                                    <Sparkles size={20} className="flex-shrink-0 mt-0.5" />
                                    <div>
                                        <p className="font-bold mb-1">{isCorrect ? 'Correct!' : 'Not quite right.'}</p>
                                        <p className="text-sm opacity-90">Reference: {currentQuestion.reference}</p>
                                    </div>
                                </div>
                                <button 
                                    onClick={handleNext}
                                    className="bg-church-900 text-white px-8 py-3 rounded-full font-bold hover:bg-black transition flex items-center gap-2 mx-auto"
                                >
                                    Next Question <Play size={16} />
                                </button>
                            </div>
                        )}
                    </div>
                )}

            </div>
        </div>
      </div>
    </div>
  );
};

export default BibleTrivia;
